project_id = "vznhbocnuykdmjvujaka"

[functions.chat]
verify_jwt = false

[functions.generate-artifact]
verify_jwt = false

[functions.generate-artifact-fix]
verify_jwt = false

[functions.generate-title]
verify_jwt = true

[functions.cache-manager]
verify_jwt = true

[functions.summarize-conversation]
verify_jwt = true

[functions.generate-image]
verify_jwt = false

[functions.bundle-artifact]
verify_jwt = false
