apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: gcr.io/buildpacks/google-22/run
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 0b9d76cf-5b91-4893-a101-cb57fa8f5f24
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/960076421399/cloud-run-source-deploy/vana-dev
    run.googleapis.com/build-name: projects/960076421399/locations/us-central1/builds/0b9d76cf-5b91-4893-a101-cb57fa8f5f24
    run.googleapis.com/build-source-location: gs://run-sources-960076421399-us-central1/services/vana-dev/1749430375.464567-4a15fee5fba94679b2e196881afd29b8.zip#1749430376476553
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://vana-dev-960076421399.us-central1.run.app","https://vana-dev-qqugqgsbcq-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: vana-dev
  namespace: '960076421399'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 523.0.1
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: lqqrcfzmkk
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 40
      containers:
      - env:
        - name: BRAVE_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: brave-api-key
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openrouter-api-key
        - name: ENVIRONMENT
          value: development
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: 'true'
        - name: GOOGLE_CLOUD_PROJECT
          value: analystai-454200
        - name: GOOGLE_CLOUD_LOCATION
          value: us-central1
        image: gcr.io/960076421399/vana-dev:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: vana-vector-search-sa@analystai-454200.iam.gserviceaccount.com
      timeoutSeconds: 600
  traffic:
  - latestRevision: true
    percent: 100
